const allProductsdata = [
  {
    id: 1,
    image: "/images/pic1.jpg",
    name: "Paracetamol Tablets",
    price: 10,
    description: "Effective pain relief and fever reducer for common ailments.",
  },
  {
    id: 2,
    image: "/images/pic2.jpg",
    name: "Digital Thermometer",
    price: 15,
    description: "Accurate and easy-to-use digital thermometer for all ages.",
  },
  {
    id: 3,
    image: "/images/pic3.jpg",
    name: "Vitamin D Supplement",
    price: 20,
    description:
      "Boost your immune system with high-quality Vitamin D capsules.",
  },
  {
    id: 4,
    image: "/images/pic4.jpg",
    name: "Blood Pressure Monitor",
    price: 25,
    description:
      "Reliable and user-friendly monitor for tracking blood pressure.",
  },
  {
    id: 5,
    image: "/images/pic5.jpg",
    name: "Antiseptic Liquid",
    price: 30,
    description:
      "Multi-purpose antiseptic for wound cleaning and disinfection.",
  },
  {
    id: 6,
    image: "/images/pic6.jpg",
    name: "Compression Bandage",
    price: 35,
    description: "Provides support and reduces swelling for injuries.",
  },
  {
    id: 7,
    image: "/images/pic7.jpg",
    name: "Cough Syrup",
    price: 40,
    description: "Soothes throat irritation and relieves persistent coughs.",
  },
  {
    id: 8,
    image: "/images/pic8.jpg",
    name: "Nebulizer Machine",
    price: 45,
    description:
      "Efficient respiratory therapy for asthma and other conditions.",
  },
  {
    id: 9,
    image: "/images/pic9.jpg",
    name: "Glucose Monitoring Kit",
    price: 50,
    description: "Essential kit for monitoring blood sugar levels accurately.",
  },
  {
    id: 10,
    image: "/images/pic10.jpg",
    name: "Surgical Mask (50 Pack)",
    price: 55,
    description: "High-quality masks for personal protection and hygiene.",
  },
  {
    id: 11,
    image: "/images/pic1.jpg",
    name: "Multivitamin Tablets",
    price: 60,
    description: "Complete daily multivitamin for overall health and wellness.",
  },
  {
    id: 12,
    image: "/images/pic2.jpg",
    name: "Pulse Oximeter",
    price: 65,
    description: "Monitor oxygen levels and pulse rate with precision.",
  },
  {
    id: 13,
    image: "/images/pic3.jpg",
    name: "Hydrocortisone Cream",
    price: 70,
    description: "Relieves itching and skin inflammation effectively.",
  },
  {
    id: 14,
    image: "/images/pic4.jpg",
    name: "Infrared Forehead Thermometer",
    price: 75,
    description:
      "Touchless thermometer for quick and hygienic temperature checks.",
  },
  {
    id: 15,
    image: "/images/pic5.jpg",
    name: "Hand Sanitizer (500ml)",
    price: 80,
    description: "Kills 99.9% of germs for effective hand hygiene.",
  },
  {
    id: 16,
    image: "/images/pic6.jpg",
    name: "Cold Compress Gel Pack",
    price: 85,
    description: "Reusable gel pack for pain relief and swelling reduction.",
  },
  {
    id: 17,
    image: "/images/pic7.jpg",
    name: "Antihistamine Tablets",
    price: 90,
    description: "Relieves symptoms of allergies and hay fever quickly.",
  },
  {
    id: 18,
    image: "/images/pic8.jpg",
    name: "First Aid Kit",
    price: 95,
    description: "Comprehensive kit for emergencies at home or on the go.",
  },
  {
    id: 19,
    image: "/images/pic9.jpg",
    name: "Antibiotic Ointment",
    price: 100,
    description: "Prevents infections and promotes healing of minor cuts.",
  },
  {
    id: 20,
    image: "/images/pic10.jpg",
    name: "Fingertip Pulse Oximeter",
    price: 105,
    description: "Portable and accurate oximeter for oxygen level monitoring.",
  },
  {
    id: 21,
    image: "/images/pic1.jpg",
    name: "Blood Glucose Strips",
    price: 110,
    description: "Compatible strips for glucose monitoring devices.",
  },
  {
    id: 22,
    image: "/images/pic2.jpg",
    name: "Hot Water Bag",
    price: 115,
    description: "Traditional therapy for aches and pains.",
  },
  {
    id: 23,
    image: "/images/pic3.jpg",
    name: "Electrolyte Powder",
    price: 120,
    description: "Rehydrates and replenishes electrolytes during illness.",
  },
  {
    id: 24,
    image: "/images/pic4.jpg",
    name: "Surgical Gloves (100 Pack)",
    price: 125,
    description: "Disposable gloves for hygiene and safety during procedures.",
  },
  {
    id: 25,
    image: "/images/pic5.jpg",
    name: "Disposable Syringes",
    price: 130,
    description: "Sterile syringes for medical use and injections.",
  },
  {
    id: 26,
    image: "/images/pic6.jpg",
    name: "CPAP Machine",
    price: 135,
    description: "Essential device for sleep apnea management.",
  },
  {
    id: 27,
    image: "/images/pic7.jpg",
    name: "Sterile Bandages",
    price: 140,
    description: "Pack of bandages for wound protection and healing.",
  },
  {
    id: 28,
    image: "/images/pic8.jpg",
    name: "Insulin Pen Needles",
    price: 145,
    description:
      "Compatible needles for insulin pens, ensuring safe injection.",
  },
  {
    id: 29,
    image: "/images/pic9.jpg",
    name: "Medical Tape",
    price: 150,
    description: "Durable and breathable tape for securing bandages.",
  },
  {
    id: 30,
    image: "/images/pic10.jpg",
    name: "Wheelchair",
    price: 155,
    description: "Lightweight and sturdy wheelchair for mobility assistance.",
  },
];

export default allProductsdata;
